language: fortran
group: travis_latest

git:
  depth: 25
  quiet: true

addons:
  apt:
    packages: ['gfortran']


matrix:
  include:
  - os: osx

install:
- cd $TRAVIS_BUILD_DIR
- mkdir install_test
- mkdir _build && cd _build
- cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/install_test
- make install
- source ../scripts/update_rpaths.sh

script: ctest
