language: generic

os:
  - osx

env:
  global:
    - CONDA_PREFIX=$HOME/conda
    - MINICONDA_URL_BASE="https://repo.continuum.io/miniconda/Miniconda3-latest"
    - TRAVIS_PYTHON_VERSION="3.*"

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      OS="MacOSX-x86_64"
    else
      OS="Linux-x86_64"
    fi
  - curl $MINICONDA_URL_BASE-$OS.sh > $HOME/miniconda.sh
  - bash $HOME/miniconda.sh -b -p $CONDA_PREFIX
  - export PATH="$CONDA_PREFIX/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda install python=$TRAVIS_PYTHON_VERSION
  - conda install gfortran_$TRAVIS_OS_NAME-64 cmake
  - source activate root

install:
  - cd $TRAVIS_BUILD_DIR
  - mkdir install_test
  - mkdir _build && cd _build
  - cmake .. -DCMAKE_INSTALL_PREFIX=$TRAVIS_BUILD_DIR/install_test
  - make install

before_script:
  - source ../scripts/update_rpaths.sh

script: 
  - cd $TRAVIS_BUILD_DIR/install_test/bin
  - ./run_bmigipl_model test.cfg
